# Generated by Django 5.0 on 2023-12-11 08:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="category",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(default=None, upload_to="courses/%Y/%m"),
        ),
        migrations.AddField(
            model_name="category",
            name="subject",
            field=models.CharField(default="SOME STRING", max_length=255),
        ),
        migrations.AddField(
            model_name="category",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(default=None, upload_to="courses/%Y/%m"),
        ),
        migrations.AlterField(
            model_name="course",
            name="subject",
            field=models.CharField(default="SOME STRING", max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("subject", "category")},
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default=None, upload_to="courses/%Y/%m")),
                ("subject", models.CharField(default="SOME STRING", max_length=255)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.course"
                    ),
                ),
            ],
            options={
                "unique_together": {("subject", "course")},
            },
        ),
    ]
