# Generated by Django 5.0 on 2023-12-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_category_active_category_created_date_category_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="lesson",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="app.tag"),
        ),
    ]
