# Generated by Django 5.0 on 2023-12-12 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_tag_lesson_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="active",
        ),
        migrations.RemoveField(
            model_name="category",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
        migrations.RemoveField(
            model_name="category",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="category",
            name="updated_date",
        ),
        migrations.AlterField(
            model_name="course",
            name="subject",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="app.course",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="subject",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="lessons", to="app.tag"
            ),
        ),
    ]
