# Generated by Django 5.0 on 2023-12-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_remove_category_active_remove_category_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(null=True, upload_to="uploads/%Y/%m"),
        ),
    ]
